version: '3.3'

services:

  devita_website:
    image: italia/developers.italia.it
    container_name: devita_website
    build:
      context: ./
      dockerfile: Dockerfile
    user: "${RUNAS?Try $ echo RUNAS=$(id -u):$(id -g) >> .env}"
    env_file:
      - .env
    ports:
      # Jekyll serve
      - 4000:4000
      # Webpack live reload
      - 35729:35729
      # webpack-dev-server
      - 8080:8080
    volumes:
      - .:/usr/src/developers.italia.it
    command: ["make", "local"]
    networks:
      - overlay

networks:
  overlay:
