version: '3.3'

services:

  elasticsearch:
    image: italia/publiccode-tools-elasticsearch:ceb40894eaa142c8aec55c8dbcc9df038ec491e1
    ports:
      - 9200:9200
    networks:
      - overlay

  devita_website:
    image: italia/developers.italia.it
    container_name: devita_website
    build:
      context: ./
      dockerfile: Dockerfile
    user: "${RUNAS?Try $ echo RUNAS=$(id -u):$(id -g) >> .env}"
    env_file:
      - .env
    ports:
      # Jekyll serve
      - 4000:4000
      # Webpack live reload
      - 35729:35729
      # webpack-dev-server
      - 8080:8080
    volumes:
      - .:/usr/src/developers.italia.it
    depends_on:
      - elasticsearch
    command: ["wait-for-it", "elasticsearch:9200", "--timeout=60", "--", "make", "local"]
    networks:
      - overlay

networks:
  overlay:
